apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-aks-ucp-learn
  namespace: ucplearn
  annotations:
    provider.platform.volvocars.com/external-name: azure-resourcegroup
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
      application: ucplearn
      createdby: akumarsr
  # the spec.providerConfigRef.name must match the ProviderConfig metadata.name value.
  providerConfigRef:
    name: azure
