apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: clusters.db.aws.bakery.volvocars.biz
  labels:
    crossplane.io/xrd: xclusters.db.aws.bakery.volvocars.biz
    provider: aws
    version: "1.0.0"
spec:
  compositeTypeRef:
    apiVersion: db.aws.bakery.volvocars.biz/v1alpha1
    kind: XCluster
  writeConnectionSecretsToNamespace: cluster-core

  patchSets:
  - name: deletionPolicyPatches
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.deletionPolicy
      toFieldPath: spec.deletionPolicy
  - name: providerPatches
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.providerConfigRef
      toFieldPath: spec.providerConfigRef.name
  - name: metadataPatches
    patches:
    - type: CombineFromComposite
      toFieldPath: metadata.name
      combine:
        variables:
          - fromFieldPath: spec.parameters.clusterName
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s-%s"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags
  - name: parameterGroupPatches
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engine
      toFieldPath: spec.forProvider.dbParameterGroupFamilySelector.engine
      transforms:
      - type: map
        map:
          mysql: aurora-mysql
          postgresql: aurora-postgresql
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engineVersion
      toFieldPath: spec.forProvider.dbParameterGroupFamilySelector.engineVersion
  - name: recordSetsPatches
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.zoneId
      toFieldPath: spec.forProvider.zoneId
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.ttl
      toFieldPath: spec.forProvider.ttl
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.providerConfigRef
      toFieldPath: spec.providerConfigRef.name
  - name: sqlConfigurations
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engine
      toFieldPath: spec.forProvider.engine
      transforms:
      - type: map
        map:
          mysql: aurora-mysql
          postgresql: aurora-postgresql
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.skipFinalSnapshot
      toFieldPath: spec.forProvider.skipFinalSnapshot

  resources:
  - name: security-group
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: SecurityGroup
      spec:
        forProvider:
          description: Allow access from the vpc
          ingress:
          - ipProtocol: TCP
            ipRanges:
            - description: Allow ingress from the vpc
              cidrIp: ${VPC_CIDR}
    patches:
    - type: PatchSet
      patchSetName: providerPatches
    - type: PatchSet
      patchSetName: metadataPatches
    - type: PatchSet
      patchSetName: deletionPolicyPatches
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.vpcId
      toFieldPath: spec.forProvider.vpcId
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engine
      toFieldPath: spec.forProvider.ingress[0].fromPort
      transforms:
      - type: map
        map:
          mysql: '3306'
          postgresql: '5432'
      - type: convert
        convert:
          toType: int
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engine
      toFieldPath: spec.forProvider.ingress[0].toPort
      transforms:
      - type: map
        map:
          mysql: '3306'
          postgresql: '5432'
      - type: convert
        convert:
          toType: int
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.groupName

  - name: cluster-parameter-group
    base: 
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: DBClusterParameterGroup
      spec:
        forProvider:
          description: The description for the DB cluster parameter group.
    patches:
    - type: PatchSet
      patchSetName: providerPatches
    - type: PatchSet
      patchSetName: metadataPatches
    - type: PatchSet
      patchSetName: parameterGroupPatches
    - type: PatchSet
      patchSetName: deletionPolicyPatches
  
  - name: parameter-group
    base:
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: DBParameterGroup
      spec:
        forProvider:
          description: The description for the DB instance parameter group.
    patches:
    - type: PatchSet
      patchSetName: providerPatches
    - type: PatchSet
      patchSetName: metadataPatches
    - type: PatchSet
      patchSetName: parameterGroupPatches
    - type: PatchSet
      patchSetName: deletionPolicyPatches

  - name: sql-cluster
    base: 
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: DBCluster
    patches:
    - type: PatchSet
      patchSetName: providerPatches
    - type: PatchSet
      patchSetName: metadataPatches
    - type: PatchSet
      patchSetName: sqlConfigurations
    - type: PatchSet
      patchSetName: deletionPolicyPatches
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.masterUsername
      toFieldPath: spec.forProvider.masterUsername
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.databaseName
      toFieldPath: spec.forProvider.databaseName
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.masterUserPasswordSecretRef
      toFieldPath: spec.forProvider.masterUserPasswordSecretRef
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.dbSubnetGroupName
      toFieldPath: spec.forProvider.dbSubnetGroupName
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.engineVersion
      toFieldPath: spec.forProvider.engineVersion
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.endpoint
      toFieldPath: status.endpoint
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.readerEndpoint
      toFieldPath: status.readerEndpoint
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.dbClusterIdentifier
      toFieldPath: status.dbClusterIdentifier
    - type: CombineFromComposite
      toFieldPath: spec.forProvider.dbClusterParameterGroupNameRef.name
      combine:
        variables:
          - fromFieldPath: spec.parameters.clusterName
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s-%s"
    - type: CombineFromComposite
      toFieldPath: spec.forProvider.vpcSecurityGroupIDRefs[0].name
      combine:
        variables:
          - fromFieldPath: spec.parameters.clusterName
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s-%s"

  - name: sql-instance-1
    base:
      apiVersion: rds.aws.crossplane.io/v1alpha1
      kind: DBInstance
      spec:
        forProvider:
          dbInstanceClass: db.t3.medium
    patches:
    - type: PatchSet
      patchSetName: providerPatches
    - type: PatchSet
      patchSetName: deletionPolicyPatches
    - type: CombineFromComposite
      toFieldPath: metadata.name
      combine:
        variables:
          - fromFieldPath: spec.parameters.clusterName
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s-%s-1"
    - type: PatchSet
      patchSetName: sqlConfigurations
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.dbInstanceClass
      toFieldPath: spec.forProvider.dbInstanceClass
    - type: CombineFromComposite
      toFieldPath: spec.forProvider.dbParameterGroupNameRef.name
      combine:
        variables:
          - fromFieldPath: spec.parameters.clusterName
          - fromFieldPath: spec.parameters.name
        strategy: string
        string:
          fmt: "%s-%s"
    - type: FromCompositeFieldPath
      fromFieldPath: status.dbClusterIdentifier
      toFieldPath: spec.forProvider.dbClusterIdentifier
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags

  - name: route-53-record-sets
    base:
      apiVersion: route53.aws.crossplane.io/v1alpha1
      kind: ResourceRecordSet
      spec:
        forProvider:
          type: CNAME
    patches:
    - type: PatchSet
      patchSetName: recordSetsPatches
    - type: PatchSet
      patchSetName: deletionPolicyPatches
    - type: FromCompositeFieldPath
      fromFieldPath: status.endpoint
      toFieldPath: spec.forProvider.resourceRecords[0].value
    - type: CombineFromComposite
      toFieldPath: metadata.name
      combine:
        variables:
          - fromFieldPath: spec.parameters.name
          - fromFieldPath: spec.parameters.clusterDomain
        strategy: string
        string:
          fmt: "%s.%s"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags

  - name: route-53-record-sets-reader
    base:
      apiVersion: route53.aws.crossplane.io/v1alpha1
      kind: ResourceRecordSet
      spec:
        forProvider:
          type: CNAME
    patches:
    - type: PatchSet
      patchSetName: recordSetsPatches
    - type: PatchSet
      patchSetName: deletionPolicyPatches
    - type: FromCompositeFieldPath
      fromFieldPath: status.readerEndpoint
      toFieldPath: spec.forProvider.resourceRecords[0].value
    - type: CombineFromComposite
      toFieldPath: metadata.name
      combine:
        variables:
          - fromFieldPath: spec.parameters.name
          - fromFieldPath: spec.parameters.clusterDomain
        strategy: string
        string:
          fmt: "%s-reader.%s"