apiVersion: resource.platform.volvocars.com/v1alpha1
kind: CustomResourcGroup
metadata:
  namespace: default
  name: claim.xresourcgroup.resource.platform.volvocars.com
spec:
  compositionRef:
    name: resourcgroup-composition
  parameters:
    resourceGroupName: rg-ucp-aks-02