apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: resourcgroup.resource.platform.volvocars.com
  labels:
    crossplane.io/xrd: xresourcgroups.resource.platform.volvocars.com
    provider: azure
    version: "1.0.0"
  annotations:
    resource.platform.volvocars.com/external-name: resourcegroup
spec:
  compositeTypeRef:
    apiVersion: resource.platform.volvocars.com/v1alpha1
    kind: XResourcGroup
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: resourcegroup
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.resourceGroupName
          toFieldPath: metadata.annotations[crossplane.io/external-name]
      base: 
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        spec:
          forProvider:
            location: West Europe
            tags:
              provisioner: crossplane-composition
              application: ucplearn
              createdby: akumarsr
          providerConfigRef:
            name: azure